# Generated by Django 4.0.1 on 2022-06-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact',
            field=models.CharField(default='000-000-0000', max_length=256),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='User', max_length=256),
        ),
    ]
